def topFiveMovies():
    print("mugen train")
    print("shang-chi")
    print("infinity war")
    print("two heroes")
    print("DBS: Broly")
topFiveMovies()
print("   ")
def topFourSports():
    print("Soccer")
    print("Skiing")
    print("Swimming")
    print("Water Tubing")
topFourSports()
print("   ")
def topFiveFoods():
    print("Alfredo")
    print("Pizza")
    print("Cheeseburger")
    print("Burrito")
    print("Chicken")
topFiveFoods()
